from django.db import models

# Create your models here.


class Player(models.Model):
    player_id = models.IntegerField()
    player_name = models.CharField(max_length=60)
    team_id = models.IntegerField()
    team_abbreviation = models.CharField(max_length=3)
    age = models.IntegerField()
    gp = models.IntegerField()
    w = models.IntegerField()
    l = models.IntegerField()
    w_pct = models.DecimalField(max_digits=3, decimal_places=1)
    min = models.DecimalField(max_digits=3, decimal_places=1)
    fgm = models.DecimalField(max_digits=3, decimal_places=1)
    fga = models.DecimalField(max_digits=3, decimal_places=1)
    fg_pct = models.DecimalField(max_digits=3, decimal_places=1)
    fg3m = models.DecimalField(max_digits=3, decimal_places=1)
    fg3a = models.DecimalField(max_digits=3, decimal_places=1)
    fg3_pct = models.DecimalField(max_digits=3, decimal_places=1)
    ftm = models.DecimalField(max_digits=3, decimal_places=1)
    fta = models.DecimalField(max_digits=3, decimal_places=1)
    ft_pct = models.DecimalField(max_digits=3, decimal_places=1)
    oreb = models.DecimalField(max_digits=3, decimal_places=1)
    dreb = models.DecimalField(max_digits=3, decimal_places=1)
    reb = models.DecimalField(max_digits=3, decimal_places=1)
    ast = models.DecimalField(max_digits=3, decimal_places=1)
    tov = models.DecimalField(max_digits=3, decimal_places=1)
    stl = models.DecimalField(max_digits=3, decimal_places=1)
    blk = models.DecimalField(max_digits=3, decimal_places=1)
    blka = models.DecimalField(max_digits=3, decimal_places=1)
    pf = models.DecimalField(max_digits=3, decimal_places=1)
    pfd = models.DecimalField(max_digits=3, decimal_places=1)
    pts = models.DecimalField(max_digits=3, decimal_places=1)
    plus_minus = models.DecimalField(max_digits=3, decimal_places=1)
    nba_fantasy_pts = models.DecimalField(max_digits=3, decimal_places=1)
    dd2 = models.DecimalField(max_digits=3, decimal_places=1)
    td3 = models.DecimalField(max_digits=3, decimal_places=1)
    gp_rank = models.IntegerField()
    w_rank = models.IntegerField()
    l_rank = models.IntegerField()
    w_pct_rank = models.IntegerField()
    min_rank = models.IntegerField()
    fgm_rank = models.IntegerField()
    fga_rank = models.IntegerField()
    fg_pct_rank = models.IntegerField()
    fg3m_rank = models.IntegerField()
    fg3a_rank = models.IntegerField()
    fg3_pct_rank = models.IntegerField()
    ftm_rank = models.IntegerField()
    fta_rank = models.IntegerField()
    ft_pct_rank = models.IntegerField()
    oreb_rank = models.IntegerField()
    dreb_rank = models.IntegerField()
    reb_rank = models.IntegerField()
    ast_rank = models.IntegerField()
    tov_rank = models.IntegerField()
    stl_rank = models.IntegerField()
    blk_rank = models.IntegerField()
    blka_rank = models.IntegerField()
    pf_rank = models.IntegerField()
    pfd_rank = models.IntegerField()
    pts_rank = models.IntegerField()
    plus_minus_rank = models.IntegerField()
    nba_fantasy_pts_rank = models.IntegerField()
    dd2_rank = models.IntegerField()
    td3_rank = models.IntegerField()
    cfid = models.IntegerField()
    cfparams = models.CharField(max_length=18)

    def __str__(self):
        name = self.player_name
        team = self.team_abbreviation
        return name + '--' + team
