# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('player_id', models.PositiveIntegerField()),
                ('player_name', models.CharField(max_length=60)),
                ('team_id', models.PositiveIntegerField()),
                ('team_abbreviation', models.CharField(max_length=3)),
                ('age', models.PositiveIntegerField()),
                ('gp', models.PositiveIntegerField()),
                ('w', models.PositiveIntegerField()),
                ('l', models.PositiveIntegerField()),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('min', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fgm', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fga', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3m', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3a', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('ftm', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fta', models.DecimalField(max_digits=4, decimal_places=3)),
                ('ft_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('oreb', models.DecimalField(max_digits=4, decimal_places=3)),
                ('dreb', models.DecimalField(max_digits=4, decimal_places=3)),
                ('reb', models.DecimalField(max_digits=4, decimal_places=3)),
                ('ast', models.DecimalField(max_digits=4, decimal_places=3)),
                ('tov', models.DecimalField(max_digits=4, decimal_places=3)),
                ('stl', models.DecimalField(max_digits=4, decimal_places=3)),
                ('blk', models.DecimalField(max_digits=4, decimal_places=3)),
                ('blka', models.DecimalField(max_digits=4, decimal_places=3)),
                ('pf', models.DecimalField(max_digits=4, decimal_places=3)),
                ('pfd', models.DecimalField(max_digits=4, decimal_places=3)),
                ('pts', models.DecimalField(max_digits=4, decimal_places=3)),
                ('plus_minus', models.DecimalField(max_digits=4, decimal_places=3)),
                ('nba_fantasy_pts', models.DecimalField(max_digits=4, decimal_places=3)),
                ('dd2', models.DecimalField(max_digits=4, decimal_places=3)),
                ('td3', models.DecimalField(max_digits=4, decimal_places=3)),
                ('gp_rank', models.PositiveIntegerField()),
                ('w_rank', models.PositiveIntegerField()),
                ('l_rank', models.PositiveIntegerField()),
                ('w_pct_rank', models.PositiveIntegerField()),
                ('min_rank', models.PositiveIntegerField()),
                ('fgm_rank', models.PositiveIntegerField()),
                ('fga_rank', models.PositiveIntegerField()),
                ('fg_pct_rank', models.PositiveIntegerField()),
                ('fg3m_rank', models.PositiveIntegerField()),
                ('fg3a_rank', models.PositiveIntegerField()),
                ('fg3_pct_rank', models.PositiveIntegerField()),
                ('ftm_rank', models.PositiveIntegerField()),
                ('fta_rank', models.PositiveIntegerField()),
                ('ft_pct_rank', models.PositiveIntegerField()),
                ('oreb_rank', models.PositiveIntegerField()),
                ('dreb_rank', models.PositiveIntegerField()),
                ('reb_rank', models.PositiveIntegerField()),
                ('ast_rank', models.PositiveIntegerField()),
                ('tov_rank', models.PositiveIntegerField()),
                ('stl_rank', models.PositiveIntegerField()),
                ('blk_rank', models.PositiveIntegerField()),
                ('blka_rank', models.PositiveIntegerField()),
                ('pf_rank', models.PositiveIntegerField()),
                ('pfd_rank', models.PositiveIntegerField()),
                ('pts_rank', models.PositiveIntegerField()),
                ('plus_minus_rank', models.PositiveIntegerField()),
                ('nba_fantasy_pts_rank', models.PositiveIntegerField()),
                ('dd2_rank', models.PositiveIntegerField()),
                ('td3_rank', models.PositiveIntegerField()),
                ('cfid', models.PositiveIntegerField()),
                ('cfparams', models.CharField(max_length=18)),
            ],
        ),
    ]
